name: Build and publish a Docker image to ghcr.io

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  packages: write
  contents: read

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: GHCR-Action
        uses: KuhlTime/ghcr-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          platforms: linux/amd64,linux/arm64
